### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by illusive-man** [phpmath/biginteger#2]
Fatal error: Uncaught Error: Call to undefined function PHP\Math\BigInteger\gmp_init() in C:\xampp\htdocs\converter\vendor\phpmath\biginteger\src\BigInteger.php on line 282
( ! ) Error: Call to undefined function PHP\Math\BigInteger\gmp_init() in C:\xampp\htdocs\converter\vendor\phpmath\biginteger\src\BigInteger.php on line 282
Call Stack
#	Time	Memory	Function	Location
1	0.2004	360824	{main}( )	...\bigtest.php:0
2	0.2023	451608	PHP\Math\BigInteger\BigInteger->__construct( )	...\bigtest.php:7
3	0.2023	451608	PHP\Math\BigInteger\BigInteger->initValue( )	...\BigInteger.php:45

**Comment by illusive-man** [comment]
If you need some details: Installed via Composer. PHP 7.1.1.

**Comment by illusive-man** [comment]
Sorry, forgot to enable php_gmp extension in php.ini. By the way it's a good idea to reflect that in readme. By default gmp is disabled in php.

**Comment by waltertamboer** [comment]
Thanks for your feedback, will update the README asap.

**Comment by waltertamboer** [comment]
@illusive-man I've just released 2.0.1 which includes a composer dependency on ext-gmp so installation will only succeed when the extension is present. I've also updated the README.

**Comment by illusive-man** [comment]
Good to know, thanks!

**Comment by illusive-man** [comment]
@waltertamboer Sorry for asking you here, but I don't know how to contact you. Can you help me a bit? I'm using your class in my library (Number to Text converter) and I encountered strange problem. When installing it with composer in a fresh directory PSR-4 autoload can see your class perfectly, but it doesn't see mine. It says 'Can not find Class ... in... blah blah'. `composer dump-autoload` didn't help, only `composer dump-autoload -o` solved the issue. But -o converts psr-4 to classmap which is not very good and it needs my interaction, but your class doesn't need it. Please, check it out if you have time. The package is on packagist.org and its name illusive-man/converter. In vendor/illusive-man/converter/ I created a sample file bigtest.php which needs to be moved to root folder, then run it from there. I'd like it to work 'out of the box' without dumping autoload first (once again - like your class). As for libraries - they both work great. Apart from the problem I encountered. Thanks in advance. Best regards, Serge.

**Comment by waltertamboer** [comment]
You should rename this file: `https://github.com/illusive-man/converter/blob/master/class/converter.php` to `Number2Text.php` as defined in the PSR-4 guideline. Class and filename should have the same name.

Luckily not a problem in this package :) Good luck :+1:

**Comment by illusive-man** [comment]
Thank you very much, Walter! That one I've missed. Now it works as it supposed to. Much appreciated! Good luck to you too!
