### ISSUE TITLE
Add the prime feature

### ISSUE THREAD

**Issue by peter279k** [phpmath/biginteger#3]
Hi @waltertamboer, thank you for your awesome project!
I need the feature of checking prime number when using this PHP package.
Would you let me add this in the package?
If possible, I can follow the rules that you suggest.

Thanks.

**Comment by waltertamboer** [comment]
Hi @peter279k !

Definitely, it's much appreciated. How will you implemenet this? Would you suggest an "isPrimeNumber" method?

Rules, long story short:
- Please add unit tests, I believe there is 100% coverage now and it would be neat to keep it that way :+1: 
- Follow the PSR guidelines to keep it readable :+1:

**Comment by peter279k** [comment]
Hi @waltertamboer, thank you for your reply.
I create the new [PR](https://github.com/phpmath/biginteger/pull/4) for this issue.
Please review this and suggest the recommendation.

Thanks.

**Comment by waltertamboer** [comment]
PR is merged, thanks!

**Comment by waltertamboer** [comment]
I've created a new release: 2.1.0

**Comment by peter279k** [comment]
Hi @waltertamboer , thank you for your reply.
One more thing I think we have to add this prime feature in Features section.

Thanks.
